"""
model_selector.py
-----------------
Per-SKU best model selection using pre-computed test-set WMAPE scores.

Reads the WMAPE JSON files generated by each model's training pipeline,
compares the scores for each SKU, and picks the winner.
Saves the lookup table as JSON for the chatbot's auto-routing.
"""

import os
import sys
import json
import pandas as pd

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(CURRENT_DIR))
ARTIFACTS_DIR = os.path.join(PROJECT_ROOT, "agent", "artifacts")

def run_model_selection(model_names: list[str] = None):
    """
    Reads saved per-SKU WMAPE files from agent/artifacts and selects the best model.
    """
    if model_names is None:
        model_names = ['lgb', 'lr', 'prophet', 'nst']
        
    print(f"\nModel Selection: Comparing {len(model_names)} models based on saved evaluation scores...")
    
    # Load all available scores
    all_scores = {}
    for model in model_names:
        path = os.path.join(ARTIFACTS_DIR, f"{model}_sku_wmape.json")
        if os.path.exists(path):
            with open(path, 'r') as f:
                all_scores[model] = json.load(f)
            print(f" - Loaded {model} scores ({len(all_scores[model])} SKUs)")
        else:
            print(f" - Warning: No saved scores found for {model} at {path}")
            
    if not all_scores:
        print("Error: No model scores found. Please run the model training scripts first.")
        return pd.DataFrame()
        
    # Get all unique SKUs across all loaded models
    all_skus = set()
    for scores in all_scores.values():
        all_skus.update(scores.keys())
        
    results = []
    lookup = {}
    
    for sku in all_skus:
        row = {"StockCode": sku}
        sku_model_scores = {}
        
        for model in all_scores:
            score = all_scores[model].get(sku)
            if score is not None:
                row[f"wmape_{model}"] = score
                sku_model_scores[model] = score
                
        if sku_model_scores:
            best = min(sku_model_scores, key=sku_model_scores.get)
            row["best_model"] = best
            row["best_wmape"] = sku_model_scores[best]
            
            lookup[sku] = {
                "model": best,
                "wmape": round(sku_model_scores[best], 2)
            }
        else:
            row["best_model"] = "lgb"  # fallback
            row["best_wmape"] = None
            
        results.append(row)
        
    results_df = pd.DataFrame(results)
    
    # Save the lookup
    os.makedirs(ARTIFACTS_DIR, exist_ok=True)
    out_path = os.path.join(ARTIFACTS_DIR, "best_model_per_sku.json")
    with open(out_path, 'w') as f:
        json.dump(lookup, f, indent=2)
        
    print(f"\nSaved best model lookup to {out_path} ({len(lookup)} SKUs)")
    
    # Print summary
    if not results_df.empty:
        print(f"\nModel Selection Summary:")
        counts = results_df['best_model'].value_counts()
        for model, count in counts.items():
            pct = count / len(results_df) * 100
            avg_wmape = results_df[results_df['best_model'] == model]['best_wmape'].mean()
            print(f"   {model.upper():>8s}: {count:4d} SKUs ({pct:5.1f}%) | Avg WMAPE: {avg_wmape:.1f}%")
            
    return results_df

if __name__ == "__main__":
    results = run_model_selection()
    if not results.empty:
        print("\n=== Model Selection Complete ===")
        print(results[['StockCode', 'best_model', 'best_wmape']].head(20).to_markdown())
